<?php
/**
 * JOBMINGTON - Public Unsubscribe Handler
 * Adds an email to the suppression list (excluded from marketing campaigns).
 * Link + token are generated by Mailer::unsubscribeUrl().
 */

define('JOBMINGTON', true);
require_once __DIR__ . '/config/env.php';
require_once __DIR__ . '/config/constants.php';
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/includes/security.php';
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/mailer.php';

$email = strtolower(trim($_GET['e'] ?? ''));
$token = trim($_GET['t'] ?? '');

$state = 'invalid'; // invalid | done | already

if ($email !== '' && filter_var($email, FILTER_VALIDATE_EMAIL) && Mailer::verifyUnsubscribeToken($email, $token)) {
    try {
        $pdo = db();
        // Table is created by the migration runner; guard in case it isn't present yet.
        $exists = $pdo->prepare("SELECT 1 FROM email_unsubscribes WHERE email = ? LIMIT 1");
        $exists->execute([$email]);
        if ($exists->fetchColumn()) {
            $state = 'already';
        } else {
            $pdo->prepare("INSERT INTO email_unsubscribes (email, reason) VALUES (?, 'user_unsubscribed')")
                ->execute([$email]);
            $state = 'done';
        }
    } catch (Throwable $e) {
        error_log('unsubscribe error: ' . $e->getMessage());
        $state = 'invalid';
    }
}

$pageTitle = 'Unsubscribe | ' . SITE_NAME;
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= e($pageTitle) ?></title>
    <link rel="preload" as="font" type="font/ttf" href="/jobmington/assets/fonts/FuturaCyrillicDemi.ttf" crossorigin>
    <link rel="preload" as="font" type="font/ttf" href="/jobmington/assets/fonts/FuturaCyrillicBook.ttf" crossorigin>
    <link rel="stylesheet" href="/jobmington/assets/css/minimal-jobmington.css?v=brand-22">
</head>
<body class="jm-minimal">
    <div class="jm-shell">
        <header class="jm-header">
            <a class="jm-logo" href="/jobmington/">
                <img src="/jobmington/assets/images/badge.png?v=logo-8" alt="">
                <span>Jobmington</span>
            </a>
            <?php require_once __DIR__ . '/includes/navigation.php'; jm_site_nav(); ?>
        </header>

        <section class="jm-section" style="padding-top:0;">
            <div class="jm-panel" style="max-width:520px;margin:48px auto;text-align:center;padding:48px 40px;">
                <?php if ($state === 'done'): ?>
                    <div style="width:64px;height:64px;border-radius:50%;background:#eef5ff;display:flex;align-items:center;justify-content:center;margin:0 auto 24px;">
                        <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#0640a3" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>
                    </div>
                    <h1 style="font-size:24px;font-weight:800;color:var(--jm-ink);margin:0 0 12px;">You're unsubscribed.</h1>
                    <p style="color:var(--jm-muted);margin:0 0 28px;line-height:1.7;"><strong><?= e($email) ?></strong> will no longer receive marketing emails from Jobmington. You'll still get essential account emails (like application updates and receipts).</p>
                    <a class="jm-button" href="/jobmington/">Back to Jobmington</a>

                <?php elseif ($state === 'already'): ?>
                    <div style="width:64px;height:64px;border-radius:50%;background:#eef5ff;display:flex;align-items:center;justify-content:center;margin:0 auto 24px;">
                        <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#0640a3" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 6 9 17l-5-5"/></svg>
                    </div>
                    <h1 style="font-size:24px;font-weight:800;color:var(--jm-ink);margin:0 0 12px;">Already unsubscribed.</h1>
                    <p style="color:var(--jm-muted);margin:0 0 28px;line-height:1.7;"><strong><?= e($email) ?></strong> is already off our marketing list. No further action needed.</p>
                    <a class="jm-button" href="/jobmington/">Back to Jobmington</a>

                <?php else: ?>
                    <div style="width:64px;height:64px;border-radius:50%;background:#fff8ee;display:flex;align-items:center;justify-content:center;margin:0 auto 24px;">
                        <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#f59f22" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
                    </div>
                    <h1 style="font-size:24px;font-weight:800;color:var(--jm-ink);margin:0 0 12px;">Link invalid or expired.</h1>
                    <p style="color:var(--jm-muted);margin:0 0 28px;line-height:1.7;">We couldn't process this unsubscribe link. Please use the link from a recent email, or contact <a href="mailto:<?= e(SITE_EMAIL) ?>" style="color:#0640a3;"><?= e(SITE_EMAIL) ?></a> and we'll remove you.</p>
                    <a class="jm-button" href="/jobmington/">Back to Jobmington</a>
                <?php endif; ?>
            </div>
        </section>

        <?php jm_minimal_footer(); ?>
    </div>
</body>
</html>
