<?php
/**
 * JOBMINGTON - Fill course modules with real lesson content (idempotent).
 * Matches modules by title and sets the full lesson body.
 *     php database/seed_module_content.php
 */
if (PHP_SAPI !== 'cli') { http_response_code(403); exit("CLI only\n"); }

define('JOBMINGTON', true);
require_once __DIR__ . '/../config/env.php';
require_once __DIR__ . '/../config/constants.php';
require_once __DIR__ . '/../config/database.php';
$pdo = db();

$lessons = [

// ── CV & Resume Masterclass ──────────────────────────────────────────────────
'Anatomy of a winning CV' =>
"A recruiter spends about seven seconds on the first scan of your CV. In that time they are not reading — they are pattern-matching, looking for signals that you might be right for the role. Your job is to make those signals impossible to miss.\n\nA strong CV has six parts, in this order:\n\n- Name and contact: your name, a professional email, phone, city, and a LinkedIn URL. Nothing else.\n- Headline: one line that states your target role, e.g. \"Product Manager - fintech, 4 years\".\n- Summary: two or three lines that combine your role, your strongest proof, and what you want.\n- Skills: 8-12 role-specific skills and tools, prioritising the words in the job description.\n- Experience: most recent first, each entry led by achievements, not duties.\n- Education and certifications: short, at the bottom.\n\nKeep it to one page early in your career, two pages at most. White space is your friend - a cramped CV signals a cramped mind. Use one clean font, consistent dates, and clear section headings.\n\nBefore you write a single bullet, read the job description twice and underline the words that repeat. Those words are the language your CV must speak. Everything that follows in this course builds on this structure.",

'Writing achievement bullets' =>
"The single biggest difference between a CV that gets interviews and one that gets ignored is the quality of the bullet points. Most people list duties. Strong candidates list results.\n\nCompare these two:\n\n- Weak: \"Responsible for managing the company's social media accounts.\"\n- Strong: \"Grew Instagram following from 2,000 to 15,000 in six months by launching a weekly content series.\"\n\nThe second one tells a recruiter exactly what you can do for them, with proof. Use this formula every time:\n\n   Action verb + what you did + measurable result.\n\nStart with a strong verb (Led, Built, Grew, Cut, Launched, Automated). Say what you actually did. Then attach a number: revenue, percentage, time saved, users supported, team size. Numbers make you credible because they are specific and hard to fake.\n\nDon't have obvious numbers? Look harder. How many people did you support? How much faster did something get? How many events did you run? Even \"handled 50+ customer queries a day\" beats \"handled customer queries\".\n\nRewrite your top five bullets right now using the formula. Lead each experience entry with your strongest, most quantified result - the recruiter may never read past the first line.",

'Beating the ATS' =>
"Most medium and large employers use an Applicant Tracking System (ATS) - software that scans, ranks, and filters CVs before a human ever sees them. If your CV is not ATS-friendly, it can be rejected automatically no matter how qualified you are.\n\nHere is how to get through:\n\n- Use a clean, single-column layout. Tables, columns, text boxes, and images confuse the parser.\n- Use standard section headings: \"Experience\", \"Education\", \"Skills\". Creative headings like \"Where I've Made Magic\" get missed.\n- Mirror the job description. If it says \"stakeholder management\" and you've done that, use those exact words - truthfully.\n- Save as a .pdf or .docx with a clear file name: Firstname-Lastname-CV.pdf.\n- Avoid headers/footers for key info; some systems ignore them.\n\nKeyword matching matters, but never lie or keyword-stuff. The goal is to make sure the real, relevant experience you already have is written in language the software recognises.\n\nA quick test: copy your CV text and paste it into a plain notepad. If the order jumbles or sections disappear, the ATS will struggle too. Fix the formatting until the plain-text version reads cleanly, top to bottom.",

'Final polish & templates' =>
"You have the structure, strong bullets, and ATS-friendly formatting. Now comes the polish that separates a good CV from a professional one.\n\nRun this 12-point checklist before every application:\n\n- Tailored to this specific job?\n- Keywords from the description included, truthfully?\n- Every experience entry led by a quantified achievement?\n- One or two pages, no more?\n- Consistent formatting - fonts, sizes, date style?\n- Professional email address?\n- No typos (read it aloud, then read it backwards)?\n- LinkedIn URL present and matching?\n- File named Firstname-Lastname-CV.pdf?\n- No personal details that invite bias (age, photo, marital status) unless required?\n- Most relevant experience near the top?\n- Saved as PDF so the layout never breaks?\n\nUse a simple, modern template - the Jobmington CV Builder produces ATS-clean layouts automatically. Avoid heavily designed templates from the internet; they often look great to you and break inside the ATS.\n\nFinally, keep a master CV with everything, then create a trimmed, tailored version for each role. Ten minutes of tailoring per application is the highest-return work in your entire job search.",

// ── Ace the Remote Job Interview ─────────────────────────────────────────────
'Before the call' =>
"Remote interviews are won or lost before you say a word. Preparation and setup do half the work.\n\nResearch first. Spend 30 minutes on the company: what they do, who their customers are, recent news, and the exact responsibilities in the job post. Write down two reasons you genuinely want this role - you will be asked.\n\nThen prepare your environment:\n\n- Test your camera, microphone, and internet the day before, and again an hour before.\n- Sit facing a window or light source so your face is well lit; avoid a bright window behind you.\n- Use a tidy, neutral background. Headphones reduce echo and signal focus.\n- Have a backup: a phone hotspot and the interviewer's number, in case your connection drops.\n- Close other apps and silence notifications.\n\nHave a few things within reach: your CV, the job description, a notepad, and a glass of water. Join two or three minutes early. Look into the camera, not the screen, when you speak - it reads as eye contact.\n\nThis preparation does more than prevent disasters. Walking in calm and ready changes how you carry yourself, and confidence is contagious.",

'The STAR method' =>
"Behavioural questions - \"Tell me about a time when...\" - are the core of most interviews. The STAR method keeps your answers clear, complete, and concise.\n\n- Situation: set the scene in one or two sentences.\n- Task: what needed to happen, and what was your responsibility.\n- Action: what YOU specifically did (not the team - you).\n- Result: the measurable outcome, and what you learned.\n\nKeep each answer to 60-90 seconds and always finish on the result. Rambling is the most common mistake; structure prevents it.\n\nThe smart move is to prepare five or six real stories from your life that you can flex to many questions: a time you solved a hard problem, handled conflict, failed and learned, led something, learned fast, or took initiative. With these ready, almost any behavioural question maps onto a story you can already tell well.\n\nPractise out loud, not just in your head - speaking is a different skill from thinking. Time yourself. The goal is to sound natural and confident, not memorised. STAR is the skeleton; your real experience is the muscle.",

'Remote-specific questions' =>
"Remote employers worry about things office employers take for granted: Can you work without supervision? Can you communicate clearly in writing? Will you get stuck and go silent?\n\nExpect questions like:\n\n- \"How do you stay productive working from home?\"\n- \"How do you communicate with a team across timezones?\"\n- \"What do you do when you're blocked and no one is online?\"\n- \"How do you organise your day?\"\n\nAnswer with concrete systems, not vibes. Don't say \"I'm very disciplined.\" Say \"I plan my day the night before, work in focused blocks, and post a short daily update so the team always knows where things stand.\" Name the tools you use - Slack, Notion, Trello, Google Calendar.\n\nFor the \"blocked\" question, show that you communicate early: you try to unblock yourself for a set time, then post a clear, specific question rather than waiting silently. That single trait - proactive communication - is what remote managers value most.\n\nIf you have remote or freelance experience, lead with it. If you don't, draw on any time you worked independently or coordinated with people you couldn't see in person.",

'Questions to ask them' =>
"When the interviewer asks \"Do you have any questions for us?\", the worst answer is \"No, I think you covered everything.\" Good questions show you think like an owner and help you decide if the job is right for you.\n\nKeep three or four ready, such as:\n\n- \"What does success look like in this role in the first 90 days?\"\n- \"What's the biggest challenge the team is facing right now?\"\n- \"How does the team communicate and collaborate day to day?\"\n- \"How do you support people working remotely?\"\n- \"What are the next steps in the process?\"\n\nAvoid asking only about salary, leave, and perks in a first interview - there is a time for that, usually once they want you. Early on, your questions should signal genuine interest in the work and the team.\n\nListen to the answers. An interview is two-way: you are also deciding whether you want to work here. If the answers about workload, support, or expectations raise red flags, that is valuable information. Asking good questions is the easiest way to end the interview on a strong, memorable note.",

// ── Freelancing Fundamentals ─────────────────────────────────────────────────
'Choosing your service' =>
"Freelancing starts with one decision: what will you sell? The mistake beginners make is staying vague - \"I do web stuff\" or \"I'm a virtual assistant.\" Vague is hard to hire.\n\nStart by matching a skill you have, or can learn quickly, to something clients actually pay for: writing, design, web development, video editing, social media management, virtual assistance, bookkeeping, or data entry. Then niche down. \"I build Shopify stores for fashion brands\" is far easier to sell than \"I make websites\", because the client instantly believes you understand their problem.\n\nA simple test for a good service: is someone already paying for it on Upwork or Fiverr? If yes, there is a market. You don't need to invent something new - you need to be clearly good at something in demand.\n\nDon't wait until you feel \"ready\". You become good by doing the work. Pick one service, complete two or three practice projects to build samples, and you have enough to start. You can always expand later. The goal of this lesson is one sentence you can say with confidence: \"I help [who] with [what].\"",

'Setting your rates' =>
"Beginners almost always undercharge, out of fear that no one will pay more. Pricing too low attracts difficult clients and burns you out.\n\nStart by researching what others charge for your service and experience level - browse profiles on Upwork and ask in freelancer communities. Set your starting rate slightly below the market to win your first few clients and reviews, then raise it every two or three projects.\n\nThere are two ways to price:\n\n- Hourly: simple to start, but caps your income and punishes you for being fast.\n- Per project: you quote a fixed price for a defined scope. As you learn to estimate well, switch to this - you get paid for the value you deliver, not the hours you spend.\n\nAlways define the scope in writing: what's included, how many revisions, and the deadline. \"Out of scope\" requests are where freelancers lose money; a clear scope lets you charge extra for extra work without friction.\n\nRemember you are running a business. Your rate must cover not just the work, but unpaid time spent finding clients, admin, and the fees on payment platforms. Charge accordingly, and raise your rates as your portfolio grows.",

'Finding your first clients' =>
"There are three reliable channels for finding clients, and the best freelancers use all three.\n\n- Marketplaces (Upwork, Fiverr): high volume and a built-in payment system. Great for your first reviews. Competition is fierce, so a sharp profile and strong proposals matter.\n- Social platforms (LinkedIn, Twitter/X): build relationships. Share useful content about your craft, comment thoughtfully, and connect with people in industries you serve. Clients come from being visible and helpful.\n- Direct outreach: identify businesses that visibly need your service and message them directly. This has less competition than marketplaces.\n\nSet a daily target - for example, ten tailored proposals or outreach messages a day. Consistency beats waiting for the perfect opportunity.\n\nLead with the client's problem, not your CV. Show you understand what they need, give one short, relevant example of your work, and end with a clear next step. Personalise the first line of every message - generic copy-paste is the fastest way to be ignored.\n\nYour first client is the hardest. Once you have a few good reviews and samples, referrals and repeat work start to compound, and finding clients gets much easier.",

'Getting paid' =>
"Landing the client is half the job; getting paid reliably is the other half. As an African freelancer working with international clients, set this up early so you're ready the moment someone wants to pay.\n\nThe main tools:\n\n- Payoneer: widely accepted, gives you receiving accounts in USD, EUR, and GBP.\n- Wise: excellent exchange rates and multi-currency balances.\n- Grey: built for Africans, with virtual foreign bank accounts.\n\nMany freelancers use a combination depending on what each client supports.\n\nTwo rules protect your income:\n\n- Take a deposit. For any new client, agree 30-50% upfront before you start. It filters out non-serious clients and protects your time. Professionals ask for deposits.\n- Invoice clearly. Send a simple, itemised invoice with your rate, the scope, the due date, and your payment details. Keep a record of every invoice for your own books and in case of a dispute.\n\nNever deliver final files before final payment. \"I'll pay once I see the finished work\" is a request to work for free. Share watermarked previews or partial work, and release the finals when payment clears.",

'Avoiding scams' =>
"Where there is freelance money, there are scams. Learning the red flags protects your time, your work, and your bank details.\n\nWalk away if a \"client\":\n\n- Asks you to pay for training, equipment, software, or a \"background check\". Real employers and clients pay you, never the other way around.\n- Refuses to pay a deposit but wants you to start immediately.\n- Asks for free \"test\" work that looks suspiciously like a real, complete task.\n- Pushes you to move off the platform immediately to avoid its protections.\n- Sends a cheque or \"overpayment\" and asks you to refund the difference - a classic fraud.\n- Has a vague identity, a brand-new account, and pressures you to act fast.\n\nProtect yourself with simple habits: use contracts or at least written scope agreements, take deposits, keep communication and payment on trusted platforms when you can, and never share banking passwords or one-time codes.\n\nTrust your instincts. If something feels rushed, too good to be true, or designed to make you pay or share sensitive details, it usually is. A real client is happy to move at a professional pace and answer reasonable questions.",

// ── Land Your First Remote Job ───────────────────────────────────────────────
'Where the remote jobs are' =>
"Finding remote work is a numbers game made smarter by looking in the right places. Spraying applications across random sites wastes your energy.\n\nFocus where remote-friendly employers actually hire:\n\n- Curated remote boards: We Work Remotely, RemoteOK, Remotive.\n- Company career pages of remote-first companies.\n- LinkedIn, filtered for \"Remote\" and your role.\n- Jobmington job alerts, tuned to your skills so the jobs come to you.\n\nApplying within 24 hours of a posting dramatically improves your odds, so set up alerts and check daily rather than binge-applying once a week.\n\nKnow which roles are most open to talent from Africa: customer support, content and copywriting, virtual assistance, sales development, data entry and analysis, design, and many junior tech roles. These are realistic entry points that don't require relocation.\n\nKeep a simple tracker - a spreadsheet with the company, role, date applied, and status. It stops you applying twice, reminds you to follow up, and turns a stressful search into a manageable routine. The goal of this lesson is a short list of three or four sources you'll check every day.",

'Building a remote-ready profile' =>
"Before you apply, make sure that when an employer looks you up, they find someone they can trust. Remote employers rely heavily on your online presence because they can't meet you in person.\n\nThree things to get right:\n\n- LinkedIn: a clear headline (your target role), a strong About section written in the first person, and experience entries that match your CV. A real photo and a complete profile build instant credibility.\n- A simple portfolio: even one page showing two or three pieces of real work. For non-creative roles, this can be a short doc describing projects and results.\n- A Talent Passport: your verified, shareable Jobmington profile that employers can trust at a glance.\n\nConsistency matters - your name, role, and key facts should match across your CV, LinkedIn, and portfolio.\n\nIf you have little formal experience, create some proof: a volunteer project, a freelance gig, a personal project, or course certificates. Employers hiring remotely are reassured by evidence they can see. A complete, consistent, credible profile turns a cold application into a warm one.",

'Applications that convert' =>
"Most applications are invisible because they are generic. A few small habits dramatically raise your reply rate.\n\n- Tailor every application. Mirror the language of the job description and address the top three requirements directly. Ten minutes per role is worth more than fifty copy-paste applications.\n- Open strong. Your first line should prove you read the post and understand the need - not \"I am writing to apply for...\". Try \"You're looking for someone who can own customer support end to end - here's how I've done exactly that.\"\n- Show proof, not adjectives. Instead of \"hard-working and detail-oriented\", give a specific result.\n- Keep it short. A focused, relevant message beats a long one.\n\nFollow up once, politely, about a week later if you haven't heard back. A short, friendly note reaffirming your interest often moves your application back to the top of the pile.\n\nFinally, apply early and apply often, but never at the cost of quality. Five tailored applications a day will out-perform fifty generic ones. Treat each application as a tiny piece of persuasive writing aimed at one specific reader.",

'Your first 30 days' =>
"Getting hired is the start, not the finish. How you show up in the first month sets your reputation and turns a probation period into a long-term role.\n\nIn week one, focus on understanding: how the team communicates, what tools they use, who does what, and what \"good\" looks like. Ask thoughtful questions and write down the answers.\n\nThroughout, master remote communication:\n\n- Over-communicate in writing. Post short, regular updates so people always know where things stand.\n- Respond promptly and keep your status visible.\n- When blocked, try to unblock yourself, then ask a clear, specific question rather than going silent.\n\nDeliver something small and useful early - a quick win builds trust fast. Be reliable: do what you say, by when you said. In remote work, dependability is visible and rare, and it makes you stand out.\n\nFinally, ask for feedback rather than waiting for it. A simple \"Is there anything I could be doing better?\" in week three shows maturity and helps you correct course early. The habits you build in these 30 days - clear communication, reliability, and initiative - are exactly what get remote workers kept, promoted, and recommended.",

// ── Personal Finance for Young Professionals ─────────────────────────────────
'Budgeting that works' =>
"A budget is not about restriction - it's about telling your money where to go before it disappears. The best budget is the simple one you'll actually keep.\n\nTry a percentage-based split of your take-home income:\n\n- Needs (around 50%): rent, food, transport, bills - the essentials.\n- Wants (around 30%): the things you enjoy but could live without.\n- Savings and goals (around 20%): emergency fund, investments, paying down debt.\n\nThese are starting points, not rules - adjust them to your reality. If your income is irregular, as it often is with freelancing, budget based on your average lower months and treat good months as a chance to save more.\n\nTrack your spending for one month so you know where your money truly goes; most people are surprised. A notebook or a free app both work.\n\nAutomate what you can: move savings out the day you get paid, before you can spend it. Paying yourself first is the single habit that most reliably builds wealth over time. Start small if you must - the amount matters less than the habit.",

'Your emergency fund' =>
"An emergency fund is money set aside for life's surprises - a lost client, a medical bill, an urgent repair. It is the foundation everything else is built on, because it stops a bad week from becoming a financial disaster.\n\nThe target: three to six months of essential expenses. That sounds like a lot, and it is - so don't aim for the whole thing at once. Start with a first goal of one month, then build from there.\n\nKeep this money separate from your everyday account, somewhere safe and easy to access but not too easy to spend - not invested in anything risky. The point is safety and availability, not growth.\n\nBuild it the same way you build any habit: automatically and consistently. Move a fixed amount the day you get paid. Even a small amount each month adds up, and the discipline matters more than the size.\n\nAn emergency fund changes how you live. It lets you turn down bad clients, leave a toxic job, and make decisions from a position of calm rather than fear. That security is one of the most valuable things money can buy.",

'Earning and saving in USD' =>
"For many people across Africa, local currency loses value over time through inflation and exchange-rate swings. Earning - and saving part of your income - in a stronger currency is one of the most powerful ways to protect your financial future.\n\nThis is the quiet superpower of remote work and freelancing: you can earn in USD, EUR, or GBP while living on local costs. Tools like Payoneer, Wise, and Grey let you receive and hold foreign currency.\n\nA few principles:\n\n- Keep part of your savings in a stable currency so it holds its value over time.\n- Only convert to local currency what you need for near-term spending.\n- Be aware of fees and exchange rates when you convert - small differences add up.\n- Never put money you can't afford to lose into anything that promises guaranteed high returns; if it sounds too good to be true, it is.\n\nYou don't need to be an investor to benefit. Simply earning globally and saving thoughtfully puts you ahead. Combined with a budget and an emergency fund, it gives you something rare and valuable: real financial stability, built on your own terms.",

];

$upd = $pdo->prepare("UPDATE course_modules SET content = ?, duration_minutes = GREATEST(duration_minutes, 18) WHERE title = ?");
$count = 0;
foreach ($lessons as $title => $body) {
    $upd->execute([$body, $title]);
    $count += $upd->rowCount();
}
echo "Module lessons updated: $count\n";
