-- Seed countries
INSERT IGNORE INTO countries (name, iso_code, region, currency_code, currency_symbol, is_active) VALUES
('Ghana', 'gh', 'West Africa', 'GHS', 'GHC', 1),
('Kenya', 'ke', 'East Africa', 'KES', 'KSh', 1),
('South Africa', 'za', 'Southern Africa', 'ZAR', 'R', 1),
('Egypt', 'eg', 'North Africa', 'EGP', 'EGP', 1),
('Tanzania', 'tz', 'East Africa', 'TZS', 'TSh', 1),
('Uganda', 'ug', 'East Africa', 'UGX', 'USh', 1),
('Rwanda', 'rw', 'East Africa', 'RWF', 'FRw', 1),
('Ethiopia', 'et', 'East Africa', 'ETB', 'Br', 1),
('Zambia', 'zm', 'Southern Africa', 'ZMW', 'ZK', 1),
('Zimbabwe', 'zw', 'Southern Africa', 'ZWL', 'ZWL', 1),
('Botswana', 'bw', 'Southern Africa', 'BWP', 'P', 1),
('Senegal', 'sn', 'West Africa', 'XOF', 'CFA', 1),
('Ivory Coast', 'ci', 'West Africa', 'XOF', 'CFA', 1),
('Cameroon', 'cm', 'Central Africa', 'XAF', 'FCFA', 1),
('Morocco', 'ma', 'North Africa', 'MAD', 'MAD', 1),
('Algeria', 'dz', 'North Africa', 'DZD', 'DZD', 1),
('Tunisia', 'tn', 'North Africa', 'TND', 'TND', 1),
('United Kingdom', 'gb', 'Europe', 'GBP', 'GBP', 1),
('United States', 'us', 'North America', 'USD', '$', 1),
('Canada', 'ca', 'North America', 'CAD', 'CAD', 1),
('Germany', 'de', 'Europe', 'EUR', 'EUR', 1),
('France', 'fr', 'Europe', 'EUR', 'EUR', 1),
('India', 'in', 'Asia', 'INR', 'INR', 1),
('United Arab Emirates', 'ae', 'Middle East', 'AED', 'AED', 1),
('Saudi Arabia', 'sa', 'Middle East', 'SAR', 'SAR', 1),
('Australia', 'au', 'Oceania', 'AUD', 'AUD', 1),
('Malawi', 'mw', 'Southern Africa', 'MWK', 'MK', 1),
('Mozambique', 'mz', 'Southern Africa', 'MZN', 'MT', 1),
('Namibia', 'na', 'Southern Africa', 'NAD', 'NAD', 1),
('Angola', 'ao', 'Southern Africa', 'AOA', 'Kz', 1),
('Mali', 'ml', 'West Africa', 'XOF', 'CFA', 1),
('Burkina Faso', 'bf', 'West Africa', 'XOF', 'CFA', 1),
('Niger', 'ne', 'West Africa', 'XOF', 'CFA', 1),
('Togo', 'tg', 'West Africa', 'XOF', 'CFA', 1),
('Benin', 'bj', 'West Africa', 'XOF', 'CFA', 1),
('Liberia', 'lr', 'West Africa', 'LRD', 'LRD', 1),
('Sierra Leone', 'sl', 'West Africa', 'SLL', 'Le', 1),
('Gambia', 'gm', 'West Africa', 'GMD', 'D', 1),
('Guinea', 'gn', 'West Africa', 'GNF', 'FG', 1),
('Democratic Republic of Congo', 'cd', 'Central Africa', 'CDF', 'FC', 1),
('Republic of Congo', 'cg', 'Central Africa', 'XAF', 'FCFA', 1),
('Gabon', 'ga', 'Central Africa', 'XAF', 'FCFA', 1),
('Chad', 'td', 'Central Africa', 'XAF', 'FCFA', 1),
('Somalia', 'so', 'East Africa', 'SOS', 'Sh', 1),
('Sudan', 'sd', 'East Africa', 'SDG', 'SDG', 1),
('South Sudan', 'ss', 'East Africa', 'SSP', 'SSP', 1),
('Eritrea', 'er', 'East Africa', 'ERN', 'Nfk', 1),
('Djibouti', 'dj', 'East Africa', 'DJF', 'Fdj', 1),
('Burundi', 'bi', 'East Africa', 'BIF', 'FBu', 1),
('Libya', 'ly', 'North Africa', 'LYD', 'LYD', 1),
('Madagascar', 'mg', 'Southern Africa', 'MGA', 'Ar', 1),
('Mauritius', 'mu', 'Southern Africa', 'MUR', 'Rs', 1),
('Seychelles', 'sc', 'Southern Africa', 'SCR', 'Rs', 1),
('Lesotho', 'ls', 'Southern Africa', 'LSL', 'L', 1),
('Eswatini', 'sz', 'Southern Africa', 'SZL', 'E', 1);
